name: Daily Bing Searches

on:
  schedule:
    - cron: "30 4 * * *"

  workflow_dispatch:

jobs:
  bing-search:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Run Bing searches
        run: python search.py